name: Build RPMs
on:
  push:
    branches:
      - master
jobs:
  build-rpms:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - 8
          - 9
    container:
      image: almalinux:${{ matrix.version }}
    env:
      RPM_SIGNER: Daniel Augustin <hossie@hossie.de>
    steps:
      - name: Install shell deps
        run: dnf install -y git jq
      - name: Fix git
        run: git config --global --add safe.directory '*'
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get Version
        run: echo "ICINGA_VER=$(./get_version.sh)" >> $GITHUB_ENV
      - name: Get Revision
        run: echo "ICINGA_REV=$(./get_revision.sh)" >> $GITHUB_ENV
      - name: Enable Repos on EL8
        run: |
          dnf -y install 'dnf-command(config-manager)'
          dnf config-manager --set-enabled powertools
        if: matrix.version == 8
      - name: Setup Build Environment
        run: |
          dnf -y install dnf-utils epel-release rpm-build rpm-sign rpmdevtools
          rpmdev-setuptree
          rpm --import icinga.key
          echo "%_gpg_name ${RPM_SIGNER}" >> /github/home/.rpmmacros
          cat /github/home/.rpmmacros
      - name: Import Key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.RPM_GPGKEY }}
      - name: Download Sources
        run: |
          curl -L -o /github/home/rpmbuild/SPECS/icinga2.spec https://git.icinga.com/packaging/rpm-icinga2/-/raw/master/icinga2.spec
          curl -L -o /github/home/rpmbuild/SOURCES/v${ICINGA_VER}.tar.gz https://github.com/Icinga/icinga2/archive/refs/tags/v${ICINGA_VER}.tar.gz
      - name: Patch Sources
        run: |
          sed -i "s/2\.11\.4/${ICINGA_VER}/g" /github/home/rpmbuild/SPECS/icinga2.spec
          sed -i "s/define revision.*/define revision ${ICINGA_REV}/g" /github/home/rpmbuild/SPECS/icinga2.spec
      - name: Build RPMs
        run: |
          yum-builddep -y /github/home/rpmbuild/SPECS/icinga2.spec
          rpmbuild -bb /github/home/rpmbuild/SPECS/icinga2.spec
          rpmsign --addsign /github/home/rpmbuild/RPMS/x86_64/icinga2*.rpm
#      - name: Create Tag
#        uses: mathieudutour/github-tag-action@v6.1
#        with:
#          custom_tag: v${{ env.ICINGA_VER }}-${{ env.ICINGA_REV }}
#          github_token: ${{ secrets.PAT }}
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.ICINGA_VER }}-${{ env.ICINGA_REV }}
          files: /github/home/rpmbuild/RPMS/x86_64/icinga2*.rpm
          body: Release Icinga RPMs ${{ env.ICINGA_VER }} (Rev. ${{ env.ICINGA_REV }})
          token: ${{ secrets.PAT }}
