name: Build RPMs
on:
  push:
jobs:
  build-rpms:
    runs-on: ubuntu-20.04
    container:
      image: almalinux:9
      env:
        ICINGA_VER: 2.13.6
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Read Version
        run: export ICINGA_TEST_VER=$(cat VERSION)
      - name: Print Version
        run: echo $ICINGA_TEST_VER
#      - name: Enable PowerTools on EL8
#        if: matrix.os == 8
#        run: |
#          dnf -y install 'dnf-command(config-manager)'
#          dnf -y config-manager --set-enabled powertools
      - name: Setup Build Environment
        run: |
          dnf -y install dnf-utils epel-release git rpm-build rpmdevtools
          rpmdev-setuptree
          git config --global --add safe.directory $GITHUB_WORKSPACE
      - name: Download Sources
        run: |
          curl -sL -o ~/rpmbuild/SPECS/icinga2.spec https://git.icinga.com/packaging/rpm-icinga2/-/raw/master/icinga2.spec
          curl -sL -o ~/rpmbuild/SOURCES/v${ICINGA_VER}.tar.gz https://github.com/Icinga/icinga2/archive/refs/tags/v${ICINGA_VER}.tar.gz
      - name: Patch Sources
        run: sed -i "s/2\.11\.4/${ICINGA_VER}/g" ~/rpmbuild/SPECS/icinga2.spec
      - name: Build RPMs
        run: |
          yum-builddep -y ~/rpmbuild/SPECS/icinga2.spec
          rpmbuild --define "revision 2" -bb ~/rpmbuild/SPECS/icinga2.spec
      - name: Create tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.ICINGA_VER }}-2
          message: test
      - name: Create release
        uses: softprops/action-gh-release@v1
#        id: create_release
        with:
          release_name: ${{ env.ICINGA_VER }}-2
          tag_name: ${{ env.ICINGA_VER }}-2
          files: ~/rpmbuild/RPMS/x86_64/icinga2*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
#      - name: Upload RPMs
#        if: ${{ github.ref == 'refs/heads/master' }}
#        uses: actions/upload-artifact@v3
#        with:
#          path: ~/rpmbuild/RPMS/x86_64/icinga2*.rpm
