name: Build RPMs
on:
  push:
    branches:
      - master
jobs:
  build-rpms:
    runs-on: ubuntu-latest
    container:
      image: almalinux:9
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Read Version
        run: echo "ICINGA_VER=$(cat VERSION)" >> $GITHUB_ENV
      - name: Read Revision
        run: echo "ICINGA_REV=$(cat REVISION)" >> $GITHUB_ENV
      - name: Setup Build Environment
        run: |
          dnf -y install dnf-utils epel-release git rpm-build rpm-sign rpmdevtools
          rpmdev-setuptree
          rpm --import icinga.key
      - name: Import Key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.RPM_GPGKEY }}
      - name: Download Sources
        run: |
          curl -L -o /github/home/rpmbuild/SPECS/icinga2.spec https://git.icinga.com/packaging/rpm-icinga2/-/raw/master/icinga2.spec
          curl -L -o /github/home/rpmbuild/SOURCES/v${ICINGA_VER}.tar.gz https://github.com/Icinga/icinga2/archive/refs/tags/v${ICINGA_VER}.tar.gz
      - name: Patch Sources
        run: |
          sed -i "s/2\.11\.4/${ICINGA_VER}/g" /github/home/rpmbuild/SPECS/icinga2.spec
          sed -i "s/define revision.*/define revision ${ICINGA_REV}/g" /github/home/rpmbuild/SPECS/icinga2.spec
      - name: Build RPMs
        run: |
          yum-builddep -y /github/home/rpmbuild/SPECS/icinga2.spec
          rpmbuild -bb /github/home/rpmbuild/SPECS/icinga2.spec
          rpmsign --addsign /github/home/rpmbuild/RPMS/x86_64/icinga2*.rpm
      - name: Create Tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          custom_tag: ${{ env.ICINGA_VER }}-${{ env.ICINGA_REV }}
          github_token: ${{ secrets.PAT }}
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.ICINGA_VER }}-${{ env.ICINGA_REV }}
          files: /github/home/rpmbuild/RPMS/x86_64/icinga2*.rpm
          body: Release Icinga RPMs ${{ env.ICINGA_VER }} (Rev. ${{ env.ICINGA_REV }})
          token: ${{ secrets.PAT }}
