name: Build RPMs

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-rpms:
    runs-on: ubuntu-22.04
    container:
      image: almalinux:${{ matrix.os }}
      env:
        ICINGA_VER: 2.13.6
    strategy:
      matrix:
        os:
          - 8
          - 9
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Enable PowerTools on EL8
        if: matrix.os == 8
        run: |
          dnf -y install 'dnf-command(config-manager)'
          dnf -y config-manager --set-enabled powertools
      - name: Setup Build Environment
        run: |
          dnf -y install dnf-utils epel-release rpm-build rpmdevtools
          rpmdev-setuptree
      - name: Download Sources
        run: |
          curl -sL -o ~/rpmbuild/SPECS/icinga2.spec https://git.icinga.com/packaging/rpm-icinga2/-/raw/master/icinga2.spec
          curl -sL -o ~/rpmbuild/SOURCES/v${ICINGA_VER}.tar.gz https://github.com/Icinga/icinga2/archive/refs/tags/v${ICINGA_VER}.tar.gz
      - name: Patch Sources
        run: sed -i "s/2\.11\.4/${ICINGA_VER}/g" ~/rpmbuild/SPECS/icinga2.spec
      - name: Build RPM
        run: |
          yum-builddep -y ~/rpmbuild/SPECS/icinga2.spec
          rpmbuild --define "revision 2" -bb ~/rpmbuild/SPECS/icinga2.spec
